### PR TITLE
Modernize Visual Studio project

### PR DESCRIPTION
**Pull request by lucianoiam**
- Make it compile on a modern Win10 computer (test on VS 2017)
- Project now points to headers installed in C:\Program Files\JACK2
- Requires ASIO SDK to be installed in C:\Program Files\asiosdk

Also:

- Recompile 64bits JackRouter for Windows and test against JACK2 1.9.16
- Remove "MINGW_deps" VS project as it is basically the same as the project in this commit
- Remove ancient VC++ 6 project

### CODE REVIEW

**Comment by lucianoiam** [comment]
Some notes:

- 32bits remains without an update both in the VS project and binary
- `regsvr32` must be run with Administrator privileges
- It is a good idea to remove key `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ASIO\JackRouter` from the registry before registering the DLL

**Comment by falkTX** [comment]
Thanks a lot!

Seeing as you have looked at the files, do they appear as if they would work in mingw?
@sletz do you perhaps know?

**Comment by lucianoiam** [comment]
frankly I don't know, sorry

**Comment by falkTX** [comment]
no worries, I feel tempted to try to build this with mingw in a branch.
for now I guess the updated binary is nice.
thanks

**Comment by falkTX** [comment]
So I took a stab at this, went a bit deep but does not really seem to be possible.
mingw does not have the needed parts to be able to build drivers (what exists is incomplete and does not even build a simple test file anyway)
there also seems to be an alternative of using stuff from MS SDK, but that would prevent us from having the files in the repository since they are not opensource.
so I am giving up on this side.

**Comment by platform-717** [comment]
Please check my comment: https://github.com/jackaudio/jack2/issues/682#issuecomment-746330840

**Pull request merged**
